import {
  BadGatewayException,
  Inject,
  Injectable,
  Logger,
  ServiceUnavailableException,
} from '@nestjs/common';
import {
  isPaywayConfigured,
  PAYWAY_CONFIG,
  type PaywaySettings,
  type ResolvedPaywayConfig,
} from './payway.config.js';
import {
  PAYWAY_CHECK_TRANSACTION_SUCCESS_CODE,
  PAYWAY_DUPLICATE_TRANSACTION_CODE,
  PAYWAY_GENERATE_QR_SUCCESS_CODE,
  PAYWAY_PATHS,
  PAYWAY_PAYMENT_OPTION,
  PAYWAY_PURCHASE_TYPE,
  PAYWAY_QR_IMAGE_TEMPLATE,
  PAYWAY_QR_LIFETIME_MINUTES,
  PAYWAY_REQUEST_TIMEOUT_MS,
  PAYWAY_TRANSACTION_STATUS,
} from './payway.constants.js';
import {
  encodePaywayBase64,
  formatPaywayRequestTime,
  signPaywayCheckTransactionRequest,
  signPaywayQrRequest,
  type PaywayQrSignable,
} from './payway-hash.js';
import {
  PAYWAY_HTTP_CLIENT,
  toDecimalOrNull,
  type PaywayCheckTransactionWireResponse,
  type PaywayGenerateQrWireResponse,
  type PaywayHttpClient,
  type PaywayQrResult,
  type PaywayTransactionCheck,
} from './payway.types.js';

/**
 * The messages this integration is willing to tell a client.
 *
 * PayWay's own `status.message` is passed straight through. That is not a leak: it is
 * the provider explaining its own refusal ("KHR Amount must be greater than 100 KHR"),
 * it names no credential, and swallowing it would leave a merchant unable to diagnose
 * a rejected QR. What must never be echoed is anything *we* sent — the request body
 * carries `hash`, and the whole point of a hash is that it is not a secret, but a log
 * line containing a valid signature for a request is one step from a log line
 * containing the key that made it.
 */
const GENERIC_PROVIDER_FAILURE_MESSAGE =
  'The payment provider could not complete the request';
const UNCONFIGURED_MESSAGE =
  'Payments are temporarily unavailable. Please try again later.';

/** What `generateQr` is asked for. Every field is server-derived. */
export interface GenerateQrInput {
  /** PayWay's `tran_id`. Generated by us, never received from a client. */
  transactionId: string;
  /** Already formatted for PayWay, so the body and the hash cannot disagree. */
  amount: string;
  currency: string;
}

/** What `checkTransaction` is asked for. */
export interface CheckTransactionInput {
  transactionId: string;
}

/**
 * The only code in this project that speaks HTTP to ABA PayWay.
 *
 * It does three things and refuses a fourth: it signs a request, sends it, and
 * validates the reply into a shape the rest of the application can trust. It does
 * **not** decide what a payment means — no amount comparison, no status mapping onto
 * our own vocabulary, no database write. Those belong to `PaymentsService`, which is
 * the only place that can see both PayWay's claim and what we stored, and a gateway
 * client that also made policy decisions would be a second, untestable copy of them.
 *
 * ## Nothing here is trusted, including the response
 *
 * PayWay answers HTTP 200 for business-level failures, so `status.code` — not the
 * HTTP status — is the authority on whether the call worked, and it is a *string* on
 * both endpoints. Every field that is later relied upon is checked for presence and
 * type before it is returned: a reply missing `qrString`, or carrying a
 * `payment_status` nobody recognises, is a failure here rather than an undefined value
 * three layers up.
 *
 * ## The API key never leaves this class
 *
 * It is read from {@link PaywayConfig}, used to sign, and dropped. There is no branch
 * that logs it, includes it in an exception, or returns it: the request body — the one
 * object that contains the derived `hash` — is never logged either. The failure paths
 * log the endpoint, the HTTP status and PayWay's own `code`/`trace_id`, which is
 * everything needed to chase a problem with PayWay's support and nothing that
 * identifies the merchant's key.
 */
@Injectable()
export class PaywayService {
  private readonly logger = new Logger(PaywayService.name);

  constructor(
    @Inject(PAYWAY_HTTP_CLIENT)
    private readonly httpClient: PaywayHttpClient,
    @Inject(PAYWAY_CONFIG)
    private readonly config: ResolvedPaywayConfig,
  ) {}


  /**
   * Mints a KHQR the customer can scan, for an amount and currency this application
   * has already fixed.
   *
   * @throws ServiceUnavailable 503 when PayWay is not configured. Distinct from a
   *   provider refusal on purpose: "we cannot reach payments" must never be
   *   mistakable for "the customer did not pay".
   * @throws BadGateway 502 when PayWay is configured but the call fails or answers
   *   with a non-success `status.code`.
   */
  async generateQr(input: GenerateQrInput): Promise<PaywayQrResult> {
    const settings = this.requireSettings();
    const reqTime = formatPaywayRequestTime();
    // The callback URL is *not* an input. It comes from validated configuration and is
    // Base64-encoded here, because the encoded form is both what gets signed and what
    // gets sent: deriving it in two layers would leave room for the two to disagree and
    // produce a hash PayWay cannot reproduce, which would present as an unexplained
    // `invalid hash` from the provider. A caller therefore cannot redirect PayWay's
    // webhooks to a URL of its own choosing, which is worth a sentence on its own.
    const callbackUrl = encodePaywayBase64(settings.callbackUrl);

    const signable: PaywayQrSignable = {
      reqTime,
      merchantId: settings.merchantId,
      transactionId: input.transactionId,
      amount: input.amount,
      currency: input.currency,
      paymentOption: PAYWAY_PAYMENT_OPTION,
      lifetimeMinutes: PAYWAY_QR_LIFETIME_MINUTES,
      qrImageTemplate: PAYWAY_QR_IMAGE_TEMPLATE,
      purchaseType: PAYWAY_PURCHASE_TYPE,
      // Every optional field is sent as an explicit empty string rather than omitted.
      // PayWay concatenates all nineteen values in a fixed order, so a field that is
      // absent from the body must still occupy its position in the signed string —
      // leaving it out would shift every later value and produce a hash PayWay cannot
      // reproduce.
      items: '',
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      callbackUrl,
      returnDeeplink: '',
      customFields: '',
      returnParams: '',
      payout: '',
    };

    const body = {
      req_time: reqTime,
      merchant_id: settings.merchantId,
      tran_id: input.transactionId,
      amount: input.amount,
      currency: input.currency,
      payment_option: signable.paymentOption,
      lifetime: signable.lifetimeMinutes,
      qr_image_template: signable.qrImageTemplate,
      purchase_type: signable.purchaseType,
      items: signable.items,
      first_name: signable.firstName,
      last_name: signable.lastName,
      email: signable.email,
      phone: signable.phone,
      callback_url: signable.callbackUrl,
      return_deeplink: signable.returnDeeplink,
      custom_fields: signable.customFields,
      return_params: signable.returnParams,
      payout: signable.payout,
      hash: signPaywayQrRequest(settings.apiKey, signable),
    };

    const response = await this.post<PaywayGenerateQrWireResponse>(
      PAYWAY_PATHS.generateQr,
      body,
      settings.baseUrl,
    );

    const code = response.status?.code;
    if (String(code) !== PAYWAY_GENERATE_QR_SUCCESS_CODE) {
      this.logProviderRefusal('generate-qr', code, response.status?.trace_id);

      // A duplicated `tran_id` means our generator collided with a live transaction.
      // It is reported distinctly because the remedy differs: a 409 says "try again"
      // to the client, where a 502 would say "the provider is broken".
      throw new BadGatewayException(
        String(code) === PAYWAY_DUPLICATE_TRANSACTION_CODE
          ? GENERIC_PROVIDER_FAILURE_MESSAGE
          : (response.status?.message ?? GENERIC_PROVIDER_FAILURE_MESSAGE),
      );
    }

    // The QR payload is the entire point of the call. A success code without one is a
    // malformed reply, not a usable QR, and returning it would hand the client a
    // payment with nothing to scan.
    const qrString = response.qrString;
    if (typeof qrString !== 'string' || qrString.length === 0) {
      this.logger.error(
        `PayWay generate-qr returned success without a qrString (trace ${response.status?.trace_id ?? 'none'})`,
      );

      throw new BadGatewayException(GENERIC_PROVIDER_FAILURE_MESSAGE);
    }

    return {
      qrString,
      qrImage: nonEmptyString(response.qrImage),
      abapayDeeplink: nonEmptyString(response.abapay_deeplink),
      lifetimeMinutes: PAYWAY_QR_LIFETIME_MINUTES,
    };
  }

  /**
   * Asks PayWay what actually happened to a transaction.
   *
   * This is the *only* trustworthy source of payment state. A callback says a payment
   * succeeded; only this call, matched against what we stored, can make that safe to
   * act on.
   *
   * The transaction id is verified against the reply's echo of it. PayWay returns the
   * id it was asked about in `status.tran_id`, and a mismatch means the reply
   * describes some other transaction — which would be a far worse bug than a timeout,
   * because it would be believed.
   *
   * @throws ServiceUnavailable 503 when PayWay is not configured.
   * @throws BadGateway 502 when the call fails, PayWay reports a non-success code, or
   *   the reply is not about the transaction that was asked for.
   */
  async checkTransaction(
    input: CheckTransactionInput,
  ): Promise<PaywayTransactionCheck> {
    const settings = this.requireSettings();
    const reqTime = formatPaywayRequestTime();
    const response = await this.post<PaywayCheckTransactionWireResponse>(
      PAYWAY_PATHS.checkTransaction,
      {
        req_time: reqTime,
        merchant_id: settings.merchantId,
        tran_id: input.transactionId,
        hash: signPaywayCheckTransactionRequest(settings.apiKey, {
          reqTime,
          merchantId: settings.merchantId,
          transactionId: input.transactionId,
        }),
      },
      settings.baseUrl,
    );

    const code = response.status?.code;
    if (String(code) !== PAYWAY_CHECK_TRANSACTION_SUCCESS_CODE) {
      this.logProviderRefusal(
        'check-transaction',
        code,
        response.status?.trace_id,
      );

      throw new BadGatewayException(
        response.status?.message ?? GENERIC_PROVIDER_FAILURE_MESSAGE,
      );
    }

    if (response.status?.tran_id !== input.transactionId) {
      // Refused rather than reported: a reply about a different transaction is not a
      // fact about this payment, and treating it as one is the failure this whole
      // verification step exists to prevent.
      this.logger.error(
        'PayWay check-transaction replied about a different transaction',
      );

      throw new BadGatewayException(GENERIC_PROVIDER_FAILURE_MESSAGE);
    }

    const data = response.data;
    const paymentStatusCode = data?.payment_status_code;
    const paymentStatus = data?.payment_status;
    const totalAmount = toDecimalOrNull(data?.total_amount);
    const paymentCurrency = data?.payment_currency;

    if (
      typeof paymentStatusCode !== 'number' ||
      typeof paymentStatus !== 'string' ||
      totalAmount === null ||
      typeof paymentCurrency !== 'string'
    ) {
      this.logger.error(
        'PayWay check-transaction returned an unusable payload',
      );

      throw new BadGatewayException(GENERIC_PROVIDER_FAILURE_MESSAGE);
    }

    // `payment_amount` is what actually left the customer's account. It is optional in
    // PayWay's schema, so a missing one falls back to `total_amount` rather than
    // leaving the caller to guess — and the caller compares it against our stored
    // amount either way, so the fallback cannot make a mismatch look like a match.
    return {
      paymentStatusCode,
      paymentStatus,
      totalAmount,
      paymentAmount: toDecimalOrNull(data?.payment_amount) ?? totalAmount,
      paymentCurrency,
      apv: nonEmptyString(data?.apv),
      transactionDate: nonEmptyString(data?.transaction_date),
    };
  }

  /**
   * Whether PayWay reports a transaction as collected.
   *
   * Requires **both** the numeric code and the status word to agree, and accepts only
   * `APPROVED`.
   *
   * `PRE-AUTH` is refused even though its code is also `0`: a pre-authorisation is a
   * hold, not a capture, and this project never requests one — so seeing it would mean
   * something other than what we asked for had happened, and confirming an order
   * against it would confirm an order nobody has paid for.
   */
  isCollected(check: PaywayTransactionCheck): boolean {
    return (
      check.paymentStatusCode === 0 &&
      check.paymentStatus === PAYWAY_TRANSACTION_STATUS.approved
    );
  }

  /**
   * Sends one signed request and parses the reply.
   *
   * A non-2xx status, an unreachable host, a timeout and an unparseable body are all
   * the same thing to a caller — we do not know what PayWay thinks — so they become one
   * 502 with one generic message. The underlying reason is logged, without the body.
   */
  private async post<T>(
    path: string,
    body: unknown,
    baseUrl: string,
  ): Promise<T> {
    let text: string;

    try {
      const response = await this.httpClient(`${baseUrl}${path}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(PAYWAY_REQUEST_TIMEOUT_MS),
      });

      text = await response.text();

      if (!response.ok) {
        this.logger.error(
          `PayWay ${path} responded with HTTP ${response.status}`,
        );

        throw new BadGatewayException(GENERIC_PROVIDER_FAILURE_MESSAGE);
      }
    } catch (error) {
      if (error instanceof BadGatewayException) {
        throw error;
      }

      // Deliberately logs the error's *name* only: an aborted request's error can
      // carry the options it was given, and those options contain the signed body.
      this.logger.error(
        `PayWay ${path} could not be reached (${errorName(error)})`,
      );

      throw new BadGatewayException(GENERIC_PROVIDER_FAILURE_MESSAGE);
    }

    try {
      return JSON.parse(text) as T;
    } catch {
      this.logger.error(`PayWay ${path} returned a body that is not JSON`);

      throw new BadGatewayException(GENERIC_PROVIDER_FAILURE_MESSAGE);
    }
  }

  /**
   * The validated settings, or a 503.
   *
   * This is the single gate between configuration and a signed request, and it is a
   * method rather than a constructor check for one reason: the application has to boot
   * without PayWay credentials so CI, a fresh clone and a cart-only deployment all
   * work. Failing here means "not configured" surfaces as a 503 on the payment route
   * and nowhere else.
   *
   * The 503 body is the same generic sentence whatever is missing, so a client cannot
   * learn anything about the deployment from a failed payment; the variable *names* go
   * to the log, which is where an operator needs them.
   *
   * The return type is `PaywaySettings` rather than a bare assertion, so the credential
   * cannot be read anywhere without having passed through here.
   */
  private requireSettings(): PaywaySettings {
    if (isPaywayConfigured(this.config)) {
      return this.config.settings;
    }

    this.logger.error(
      `PayWay is not configured; missing ${this.config.missing.join(', ')}`,
    );

    throw new ServiceUnavailableException(UNCONFIGURED_MESSAGE);
  }

  /** Records a business-level refusal using only provider-supplied identifiers. */
  private logProviderRefusal(
    endpoint: string,
    code: string | number | undefined,
    traceId: string | undefined,
  ): void {
    this.logger.warn(
      `PayWay ${endpoint} refused the request (code ${String(code)}, trace ${traceId ?? 'none'})`,
    );
  }
}

/** A string that is present and not blank, or `undefined`. */
function nonEmptyString(value: string | undefined): string | undefined {
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

/** An error's class name, for a log line that must not carry the error itself. */
function errorName(error: unknown): string {
  return error instanceof Error ? error.name : 'unknown';
}
